Fix an error while running this under docker-compose 1.7
```
$ docker-compose up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
mysql.environment.MYSQL_ALLOW_EMPTY_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null
```